name: New Boundary access request

on:
  issues:
    types: [opened]

jobs:
  provide-access:
    env:
      BOUNDARY_ADDR: ${{ vars.BOUNDARY_ADDR }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Creator: ${{ github.event.issues.issue.user.email }}"
      - name: Install Boundary
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install boundary
      - name: Sign-in to Boundary
        run: |
          BOUNDARY_TOKEN=$(boundary authenticate password \
            -format=json \
            -keyring-type=none \
            -login-name=${{ vars.BOUNDARY_USERNAME }} \
            -password=env://BOUNDARY_PASSWORD | jq -r '.item.attributes.token')

            # set the boundary token as en environment variable for later steps
            echo "BOUNDARY_TOKEN=$BOUNDARY_TOKEN" >> $GITHUB_ENV
        env:
          BOUNDARY_PASSWORD: ${{ secrets.BOUNDARY_PASSWORD }}
      - name: List all scopes
        run: |
          boundary scopes list -recursive -token env://BOUNDARY_TOKEN
 